/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import clases.Servicio;
import clases.Usuario;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame implements iAcciones {
    static ArrayList<Servicio> usuarioServicio = new ArrayList<Servicio>();
    /**
     * Creates new form IniciarSecion
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMedPag = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jCcantidad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPrecioTotal = new javax.swing.JTextField();
        jCanMax = new javax.swing.JTextField();
        jCTipoServis = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPrecioo = new javax.swing.JTextField();
        jTiemSer = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxComen = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jApellido = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jDni = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jProcedencia = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jAnioo = new javax.swing.JTextField();
        jMess = new javax.swing.JTextField();
        jDiaa = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jAniodeNac = new javax.swing.JLabel();
        jMes = new javax.swing.JLabel();
        jDia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BAÑOS DEL INCA");

        jLabel2.setText("Servicio");

        jLabel3.setText("Medio de pago");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Imprimir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMedPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Visa", "MasterCard" }));

        jLabel4.setText("cantidad de entradas");

        jCcantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jCcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcantidadActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad de entradas máximas");

        jLabel7.setText("Precio Total");

        jCanMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCanMaxActionPerformed(evt);
            }
        });

        jCTipoServis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sauna", "Piscina", "Parque" }));
        jCTipoServis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCTipoServisMouseClicked(evt);
            }
        });
        jCTipoServis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTipoServisActionPerformed(evt);
            }
        });

        jLabel8.setText("tiempo de atención del servicio");

        jPrecioo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPreciooActionPerformed(evt);
            }
        });
        jPrecioo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPreciooKeyTyped(evt);
            }
        });

        jLabel9.setText("Tiempo Personal");

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("NOTA: el campo servicio debe llenarse al final");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_ini_sesion/baños del inca.png"))); // NOI18N

        jLabel12.setText("Comentario");

        jButton4.setText("Guardar Comentario");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel13.setText("Precio ");

        jNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombreActionPerformed(evt);
            }
        });
        jNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNombreKeyTyped(evt);
            }
        });

        jLabel5.setText("Nombre");

        jApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jApellidoKeyTyped(evt);
            }
        });

        jLabel14.setText("Apellidos");

        jDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDniKeyTyped(evt);
            }
        });

        jLabel15.setText("D.N.I");

        jProcedencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProcedenciaActionPerformed(evt);
            }
        });
        jProcedencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jProcedenciaKeyTyped(evt);
            }
        });

        jLabel16.setText("Procedencia");

        jAnioo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAniooActionPerformed(evt);
            }
        });
        jAnioo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jAniooKeyTyped(evt);
            }
        });

        jMess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jMessKeyTyped(evt);
            }
        });

        jDiaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDiaaKeyTyped(evt);
            }
        });

        jLabel17.setText("Fecha Nacimiento");

        jAniodeNac.setText("Año");

        jMes.setText("Mes");

        jDia.setText("Día");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel14)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(53, 53, 53))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jtxComen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPrecioTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPrecioo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3))
                                                .addGap(48, 48, 48))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4))
                                                .addGap(32, 32, 32)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jCcantidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jMedPag, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCTipoServis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel8)))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTiemSer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCanMax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jDni, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jAnioo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jAniodeNac)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jMess, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jMes)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDiaa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(170, 170, 170))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)))
                        .addComponent(jLabel11)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCTipoServis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCanMax, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMedPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTiemSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxComen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPrecioo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAnioo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMess, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDiaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAniodeNac)
                    .addComponent(jMes)
                    .addComponent(jDia))
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCcantidadActionPerformed

    private void jCTipoServisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTipoServisActionPerformed
       Scanner leer = new Scanner(System.in);
       double tiem = 0;
        String nCuenta,clave;
    String vTipo,mPago;
    int cantidad,precio = 0;
    vTipo= jCTipoServis.getSelectedItem().toString();
    cantidad= Integer.parseInt((String) jCcantidad.getSelectedItem());
    mPago= jMedPag.getSelectedItem().toString();
    if("Sauna".equals(vTipo)){
        jPrecioo.setText("S/. 5");
        precio =5;
         jPrecioTotal.setText("S/."+precio*cantidad);
         jCanMax.setText("6");
         jTiemSer.setText("4 am - 5 pm");
         jTextField1.setText("30 min");
         tiem = 30;
         if(("Visa".equals(mPago)) ||("MasterCard".equals(mPago)) ){
             nCuenta = JOptionPane.showInputDialog("NUMERO DE CUENTA");
             clave = JOptionPane.showInputDialog("CLAVE");
             JOptionPane.showMessageDialog(this,"Se desconto: s/. "+(precio*cantidad)+" de su tarjeta con EXITO");
         }
    }else if("Piscina".equals(vTipo)){
        jPrecioo.setText("S/. 4");
        precio =4;
         jPrecioTotal.setText("S/."+precio*cantidad);
         jCanMax.setText("20");
         jTiemSer.setText("4 am - 6 pm");
         jTextField1.setText("60 min");
         tiem = 60;
         if(("Visa".equals(mPago)) ||("MasterCard".equals(mPago)) ){
             nCuenta = JOptionPane.showInputDialog("NUMERO DE CUENTA");
             clave = JOptionPane.showInputDialog("CLAVE");
             JOptionPane.showMessageDialog(this,"Se desconto: s/. "+(precio*cantidad)+" de su tarjeta con EXITO");
         }
    }else if("Parque".equals(vTipo)){
        jPrecioo.setText("S/. 3");
        precio =3;
         jPrecioTotal.setText("S/."+precio*cantidad);
         jCanMax.setText("250");
         jTiemSer.setText("4 am - 7 pm");
         jTextField1.setText("2 hrs");
         tiem = 120;
         if(("Visa".equals(mPago)) ||("MasterCard".equals(mPago)) ){
             nCuenta = JOptionPane.showInputDialog("NUMERO DE CUENTA");
             clave = JOptionPane.showInputDialog("CLAVE");
             JOptionPane.showMessageDialog(this,"Se desconto: s/. "+(precio*cantidad)+" de su tarjeta con EXITO");
         }
    }
  
    
    }//GEN-LAST:event_jCTipoServisActionPerformed

    private void jCTipoServisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCTipoServisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTipoServisMouseClicked

    private void jPreciooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPreciooActionPerformed
        
    }//GEN-LAST:event_jPreciooActionPerformed

    private void jCanMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCanMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCanMaxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        guardar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        imprimir();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPreciooKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPreciooKeyTyped
        char caracter = evt.getKeyChar();
      if(Character.isDigit(caracter)){
          
      }else{
          evt.consume();
      }
    }//GEN-LAST:event_jPreciooKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String x;
       x=jCTipoServis.getSelectedItem().toString();
        
        String FILE_NAM = ("Comentario para "+x+".txt");
        try{
           
            FileWriter output = new FileWriter(FILE_NAM);
            
            String text = jtxComen.getText();
            for (int i = 0; i < text.length(); i++) {
          
               output.write(text.charAt(i));
              
                   
            }
            
            
            output.close();
        }
        catch(IOException ex){
            System.out.println(";(");
        }
        JOptionPane.showMessageDialog(this,"Guardado con Exito ");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombreActionPerformed

    private void jNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNombreKeyTyped
        char caracter = evt.getKeyChar();
        if(Character.isLetter(caracter)){

        }else{
            evt.consume();
        }
    }//GEN-LAST:event_jNombreKeyTyped

    private void jApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jApellidoKeyTyped
        char caracter = evt.getKeyChar();
        if(Character.isLetter(caracter)){

        }else{
            evt.consume();
        }
    }//GEN-LAST:event_jApellidoKeyTyped

    private void jDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDniKeyTyped
        char caracter = evt.getKeyChar();
        if(Character.isDigit(caracter)){

        }else{
            evt.consume();
        }
    }//GEN-LAST:event_jDniKeyTyped

    private void jProcedenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProcedenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProcedenciaActionPerformed

    private void jProcedenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jProcedenciaKeyTyped
        char caracter = evt.getKeyChar();
        if(Character.isLetter(caracter)){

        }else{
            evt.consume();
        }
    }//GEN-LAST:event_jProcedenciaKeyTyped

    private void jAniooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAniooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAniooActionPerformed

    private void jAniooKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAniooKeyTyped
        char caracter = evt.getKeyChar();
        if(Character.isDigit(caracter)){

        }else{
            evt.consume();
        }
    }//GEN-LAST:event_jAniooKeyTyped

    private void jMessKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMessKeyTyped
        char caracter = evt.getKeyChar();
        if(Character.isDigit(caracter)){

        }else{
            evt.consume();
        }
    }//GEN-LAST:event_jMessKeyTyped

    private void jDiaaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDiaaKeyTyped
        char caracter = evt.getKeyChar();
        if(Character.isDigit(caracter)){

        }else{
            evt.consume();
        }
    }//GEN-LAST:event_jDiaaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAniodeNac;
    private javax.swing.JTextField jAnioo;
    private javax.swing.JTextField jApellido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCTipoServis;
    private javax.swing.JTextField jCanMax;
    private javax.swing.JComboBox<String> jCcantidad;
    private javax.swing.JLabel jDia;
    private javax.swing.JTextField jDiaa;
    private javax.swing.JTextField jDni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jMedPag;
    private javax.swing.JLabel jMes;
    private javax.swing.JTextField jMess;
    private javax.swing.JTextField jNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPrecioTotal;
    private javax.swing.JTextField jPrecioo;
    private javax.swing.JTextField jProcedencia;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTiemSer;
    private javax.swing.JTextField jtxComen;
    // End of variables declaration//GEN-END:variables

    @Override
    
    public void guardar() {
     String n,a,d,p;
        int anio,mes,dia; 
        n = jNombre.getText();
        a = jApellido.getText();
        d = jDni.getText(); 
        p = jProcedencia.getText();
        anio= Integer.parseInt(jAnioo.getText());
        mes= Integer.parseInt(jMess.getText());
        dia= Integer.parseInt(jDiaa.getText());
        
        
    double tiem = 0;
    String vTipo;
    int cantidad,precio = 0;
    vTipo= jCTipoServis.getSelectedItem().toString();
    cantidad= Integer.parseInt((String) jCcantidad.getSelectedItem());
    if("Sauna".equals(vTipo)){
        precio =5*cantidad;
         tiem = 30;
         
        /* Iterator <Usuario> it;
        Usuario e;
        it = us.iterator();
        while (it.hasNext()){
            e = it.next();
            JOptionPane.showMessageDialog(this, e.toString());
        }*/
         Servicio s = new Servicio(tiem, cantidad, precio, vTipo, n, a, d, p, anio, mes, dia);
         //double tiempo, int cantidad, int precio, String tipo, String nombre, String apellido, String dni, String procedencia, int anio, int mes, int dia)
        usuarioServicio.add(s);
    JOptionPane.showMessageDialog(this,"Guardado con Exito ");
    
     String FILE_NAME = ("Registro servicio de "+s.getTipo()+" "+s.getNombre()+".txt");
        try{
           
            FileWriter output = new FileWriter(FILE_NAME);
            
            output.write(s.getNombre());
            output.write(s.getApellido());
            output.write(s.getDni());
            output.write(s.getProcedencia());
            output.write(s.getAnio()+"");
            output.write(s.getMes()+"");
            output.write(s.getDia()+"");
            
            output.write((int) s.getTiempo()+"");
            output.write(s.getCantidad()+"");
            output.write(s.getPrecio()+"");
            output.write(s.getTipo());
            
            
            output.close();
        }
        catch(IOException ex){
            System.out.println(";(");
        }
        
        
         
    }else if("Piscina".equals(vTipo)){
        
        precio =4*cantidad;
         
         tiem = 60;
        Servicio s = new Servicio(tiem, cantidad, precio, vTipo, n, a, d, p, anio, mes, dia);
    usuarioServicio.add(s);
    JOptionPane.showMessageDialog(this,"Guardado con Exito ");
    
    
    String FILE_NAME = ("Registro servicio de "+s.getTipo()+" "+s.getNombre()+".txt");
        try{
           
            FileWriter output = new FileWriter(FILE_NAME);
            
            output.write(s.getNombre());
            output.write(s.getApellido());
            output.write(s.getDni());
            output.write(s.getProcedencia());
            output.write(s.getAnio()+"");
            output.write(s.getMes()+"");
            output.write(s.getDia()+"");
            
            output.write((int) s.getTiempo()+"");
            output.write(s.getCantidad()+"");
            output.write(s.getPrecio()+"");
            output.write(s.getTipo());
            
            
            output.close();
        }
        catch(IOException ex){
            System.out.println(";(");
        }
        
        
    }else if("Parque".equals(vTipo)){
        
        precio =3*cantidad;
         
         tiem = 120;
         Servicio s = new Servicio(tiem, cantidad, precio, vTipo, n, a, d, p, anio, mes, dia);
    usuarioServicio.add(s);
    JOptionPane.showMessageDialog(this,"Guardado con Exito ");
    
    
    String FILE_NAME = ("Registro servicio de "+s.getTipo()+" "+s.getNombre()+".txt");
        try{
           
            FileWriter output = new FileWriter(FILE_NAME);
            
            output.write(s.getNombre());
            output.write(s.getApellido());
            output.write(s.getDni());
            output.write(s.getProcedencia());
            output.write(s.getAnio()+"");
            output.write(s.getMes()+"");
            output.write(s.getDia()+"");
            
            output.write((int) s.getTiempo()+"");
            output.write(s.getCantidad()+"");
            output.write(s.getPrecio()+"");
            output.write(s.getTipo());
            
            
            output.close();
        }
        catch(IOException ex){
            System.out.println(";(");
        }
        
        
    }
    
    
    
    }
    
    
    public void imprimir() {
        double tiem = 0;
    String vTipo;
    int cantidad,precio = 0;
    vTipo= jCTipoServis.getSelectedItem().toString();
    cantidad= Integer.parseInt((String) jCcantidad.getSelectedItem());
    if("Sauna".equals(vTipo)){
        precio =5*cantidad;
         tiem = 30;
         
    }else if("Piscina".equals(vTipo)){
        
        precio =4*cantidad;
         
         tiem = 60;
         
    }else if("Parque".equals(vTipo)){
        
        precio =3*cantidad;
         
         tiem = 120;
    }
        JOptionPane.showMessageDialog(this, "Servicio: "+vTipo+
                "\nCatidad de entradas: "+cantidad+
                "\nPrecio total: "+precio+
                "\nTiempo Personal: "+tiem);
    }

    @Override
    public void limpiar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
